import React, { createContext, useContext, useReducer, useEffect } from 'react';
import { toast } from 'react-toastify';

const LanguageContext = createContext();

const initialState = {
  currentLanguage: 'en',
  translations: {
    en: {
      // Patient Registration
      'patient.registration': 'Patient Registration',
      'patient.emergency': 'Emergency Registration',
      'patient.basicInformation': 'Basic Information',
      'patient.extendedDemographics': 'Extended Demographics',
      'patient.medicalInformation': 'Medical Information',
      'patient.allergies': 'Allergies & Sensitivities',
      'patient.allergyName': 'Allergy Name',
      'patient.severity': 'Severity',
      'patient.active': 'Active',
      'patient.inactive': 'Inactive',
      'patient.reaction': 'Reaction/Symptoms',
      'patient.onsetDate': 'Onset Date',
      'patient.notes': 'Notes',
      'patient.criticalAllergies': 'Critical Allergies Detected',
      'patient.criticalAllergiesWarning': 'Patient has severe or life-threatening allergies. Ensure proper precautions are taken.',
      'patient.noAllergies': 'No allergies recorded',
      'patient.allergySummary': 'Allergy Summary',
      'patient.bloodGroup': 'Blood Group',
      'patient.medicalHistory': 'Medical History',
      'patient.medicalHistoryPlaceholder': 'Enter any relevant medical history...',
      'patient.medications': 'Current Medications',
      'patient.medicationsPlaceholder': 'List current medications...',
      'patient.chronicConditions': 'Chronic Conditions',
      'patient.chronicConditionsPlaceholder': 'Enter chronic conditions separated by commas...',
      'patient.basicInfo': 'Basic Info',
      'patient.medical': 'Medical',
      'patient.extended': 'Extended',
      'patient.consent': 'Consent',
      'patient.emergencyModeActive': 'Emergency Mode Active - Reduced data requirements for quick registration',
      'patient.emergencyModeDescription': 'Only basic information and one biometric are required. Full registration can be completed later.',
      
      // Allergy severity levels
      'allergy.severity.mild': 'Mild',
      'allergy.severity.moderate': 'Moderate',
      'allergy.severity.severe': 'Severe',
      'allergy.severity.life_threatening': 'Life-threatening',
      
      // Common
      'common.save': 'Save',
      'common.cancel': 'Cancel',
      'common.submit': 'Submit',
      'common.submitting': 'Submitting...',
      'common.edit': 'Edit',
      'common.delete': 'Delete',
      'common.view': 'View',
      'common.loading': 'Loading...',
      'common.error': 'Error',
      'common.success': 'Success',
      'common.warning': 'Warning',
      'common.info': 'Information',
      'common.back': 'Back',
      'common.next': 'Next',
      'common.formComplete': 'All required fields are completed. You can submit the form.',
      'common.formIncomplete': 'Please complete all required fields to enable form submission.',
      'common.formStatus': 'Form Completion Status',
      'common.completeRequiredFields': 'Complete Required Fields',
      'common.registerPatient': 'Register Patient',
      'common.quickRegisterPatient': 'Quick Register Patient',
      'common.registeringPatient': 'Registering Patient...',
      'common.addAllergy': 'Add Allergy',
      'common.removeAllergy': 'Remove Allergy',
      'common.keyboardShortcuts': 'Keyboard Shortcuts',
      'common.navigation': 'Navigation',
      'common.formActions': 'Form Actions',
      'common.emergencyMode': 'Emergency Mode',
      'common.biometric': 'Biometric',
      'common.help': 'Help',
      'common.close': 'Close',
      'common.ocrProcessing': 'OCR Document Processing',
      'common.uploadDocuments': 'Upload Documents',
      'common.uploadDocumentsDescription': 'Upload Aadhaar Card, PAN Card, or Ration Card for automatic data extraction',
      'common.selectDocuments': 'Select Documents',
      'common.uploadedDocuments': 'Uploaded Documents',
      'common.ocrResults': 'OCR Processing Results',
      'common.processingDocuments': 'Processing documents...',
      'common.noDocumentsProcessed': 'No documents processed yet',
      'common.name': 'Name',
      'common.dateOfBirth': 'Date of Birth',
      'common.address': 'Address',
      'common.aadhaarNumber': 'Aadhaar Number',
      'common.panNumber': 'PAN Number',
      'common.familyMembers': 'Family Members',
      'common.applyToForm': 'Apply to Form',
      'common.reprocess': 'Reprocess',
      'common.processAll': 'Process All Documents',
      'common.multiFactorAuth': 'Multi-Factor Authentication',
      'common.updateType': 'Update Type',
      'common.fieldToUpdate': 'Field',
      'common.verificationSteps': 'Verification Steps',
      'common.step1': 'Step 1',
      'common.step2': 'Step 2',
      'common.step3': 'Step 3',
      'common.biometricVerification': 'Biometric Verification',
      'common.biometricVerificationDescription': 'Please provide biometric verification to proceed with the update',
      'common.biometricVerified': 'Biometric Verified',
      'common.verifyBiometric': 'Verify Biometric',
      'common.otpVerification': 'OTP Verification',
      'common.otpVerificationDescription': 'Enter the OTP sent to your registered mobile number',
      'common.sendOTP': 'Send OTP',
      'common.enterOTP': 'Enter OTP',
      'common.documentUpload': 'Document Upload',
      'common.documentUploadDescription': 'Upload supporting document for critical update verification',
      'common.uploadDocument': 'Upload Document',
      'common.documentUploaded': 'Document Uploaded',
      'common.verificationProgress': 'Verification Progress',
      'common.cancel': 'Cancel',
    },
    
    hi: {
      // Patient Registration
      'patient.registration': 'रोगी पंजीकरण',
      'patient.emergency': 'आपातकालीन पंजीकरण',
      'patient.basicInformation': 'मूल जानकारी',
      'patient.extendedDemographics': 'विस्तारित जनसांख्यिकी',
      'patient.medicalInformation': 'चिकित्सीय जानकारी',
      'patient.allergies': 'एलर्जी और संवेदनशीलता',
      'patient.allergyName': 'एलर्जी का नाम',
      'patient.severity': 'गंभीरता',
      'patient.active': 'सक्रिय',
      'patient.inactive': 'निष्क्रिय',
      'patient.reaction': 'प्रतिक्रिया/लक्षण',
      'patient.onsetDate': 'शुरुआत की तारीख',
      'patient.notes': 'टिप्पणियां',
      'patient.criticalAllergies': 'गंभीर एलर्जी का पता चला',
      'patient.criticalAllergiesWarning': 'रोगी को गंभीर या जीवन-धमकी देने वाली एलर्जी है। उचित सावधानियां बरतें।',
      'patient.noAllergies': 'कोई एलर्जी दर्ज नहीं की गई',
      'patient.allergySummary': 'एलर्जी सारांश',
      'patient.bloodGroup': 'रक्त समूह',
      'patient.medicalHistory': 'चिकित्सीय इतिहास',
      'patient.medicalHistoryPlaceholder': 'कोई प्रासंगिक चिकित्सीय इतिहास दर्ज करें...',
      'patient.medications': 'वर्तमान दवाएं',
      'patient.medicationsPlaceholder': 'वर्तमान दवाओं की सूची...',
      'patient.chronicConditions': 'पुरानी स्थितियां',
      'patient.chronicConditionsPlaceholder': 'अल्पविराम से अलग किए गए पुराने रोग दर्ज करें...',
      'patient.basicInfo': 'मूल जानकारी',
      'patient.medical': 'चिकित्सीय',
      'patient.extended': 'विस्तारित',
      'patient.consent': 'सहमति',
      'patient.emergencyModeActive': 'आपातकालीन मोड सक्रिय - त्वरित पंजीकरण के लिए कम डेटा आवश्यकताएं',
      'patient.emergencyModeDescription': 'केवल मूल जानकारी और एक बायोमेट्रिक की आवश्यकता है। पूर्ण पंजीकरण बाद में पूरा किया जा सकता है।',
      
      // Allergy severity levels
      'allergy.severity.mild': 'हल्की',
      'allergy.severity.moderate': 'मध्यम',
      'allergy.severity.severe': 'गंभीर',
      'allergy.severity.life_threatening': 'जीवन-धमकी',
      
      // Common
      'common.save': 'सहेजें',
      'common.cancel': 'रद्द करें',
      'common.submit': 'जमा करें',
      'common.submitting': 'जमा हो रहा है...',
      'common.edit': 'संपादित करें',
      'common.delete': 'हटाएं',
      'common.view': 'देखें',
      'common.loading': 'लोड हो रहा है...',
      'common.error': 'त्रुटि',
      'common.success': 'सफलता',
      'common.warning': 'चेतावनी',
      'common.info': 'जानकारी',
      'common.back': 'वापस',
      'common.next': 'अगला',
      'common.formComplete': 'सभी आवश्यक फ़ील्ड पूर्ण हैं। आप फ़ॉर्म को जमा कर सकते हैं।',
      'common.formIncomplete': 'कृपया सभी आवश्यक फ़ील्ड पूर्ण करें जिससे फ़ॉर्म जमा करने की सहायता हो।',
      'common.formStatus': 'फ़ॉर्म पूर्णता स्थिति',
      'common.completeRequiredFields': 'आवश्यक फ़ील्ड पूर्ण करें',
      'common.registerPatient': 'रोगी पंजीकरण',
      'common.quickRegisterPatient': 'तेज़ रोगी पंजीकरण',
      'common.registeringPatient': 'रोगी पंजीकरण हो रहा है...',
      'common.addAllergy': 'एलर्जी जोड़ें',
      'common.removeAllergy': 'एलर्जी हटाएं',
      'common.keyboardShortcuts': 'कीबोर्ड शॉर्टकट',
      'common.navigation': 'नेविगेशन',
      'common.formActions': 'फॉर्म कार्य',
      'common.emergencyMode': 'आपातकालीन मोड',
      'common.biometric': 'बायोमेट्रिक',
      'common.help': 'सहायता',
      'common.close': 'बंद करें',
      'common.ocrProcessing': 'OCR दस्तावेज़ प्रसंस्करण',
      'common.uploadDocuments': 'दस्तावेज़ अपलोड करें',
      'common.uploadDocumentsDescription': 'स्वचालित डेटा निष्कर्षण के लिए आधार कार्ड, पैन कार्ड, या राशन कार्ड अपलोड करें',
      'common.selectDocuments': 'दस्तावेज़ चुनें',
      'common.uploadedDocuments': 'अपलोड किए गए दस्तावेज़',
      'common.ocrResults': 'OCR प्रसंस्करण परिणाम',
      'common.processingDocuments': 'दस्तावेज़ प्रसंस्करण हो रहा है...',
      'common.noDocumentsProcessed': 'अभी तक कोई दस्तावेज़ प्रसंस्कृत नहीं हुआ',
      'common.name': 'नाम',
      'common.dateOfBirth': 'जन्म तिथि',
      'common.address': 'पता',
      'common.aadhaarNumber': 'आधार संख्या',
      'common.panNumber': 'पैन संख्या',
      'common.familyMembers': 'परिवार के सदस्य',
      'common.applyToForm': 'फॉर्म में लागू करें',
      'common.reprocess': 'पुनः प्रसंस्करण',
      'common.processAll': 'सभी दस्तावेज़ प्रसंस्करण करें',
      'common.multiFactorAuth': 'बहु-कारक प्रमाणीकरण',
      'common.updateType': 'अपडेट प्रकार',
      'common.fieldToUpdate': 'फील्ड',
      'common.verificationSteps': 'सत्यापन चरण',
      'common.step1': 'चरण 1',
      'common.step2': 'चरण 2',
      'common.step3': 'चरण 3',
      'common.biometricVerification': 'बायोमेट्रिक सत्यापन',
      'common.biometricVerificationDescription': 'कृपया अपडेट जारी रखने के लिए बायोमेट्रिक सत्यापन प्रदान करें',
      'common.biometricVerified': 'बायोमेट्रिक सत्यापित',
      'common.verifyBiometric': 'बायोमेट्रिक सत्यापित करें',
      'common.otpVerification': 'OTP सत्यापन',
      'common.otpVerificationDescription': 'अपने पंजीकृत मोबाइल नंबर पर भेजे गए OTP को दर्ज करें',
      'common.sendOTP': 'OTP भेजें',
      'common.enterOTP': 'OTP दर्ज करें',
      'common.documentUpload': 'दस्तावेज़ अपलोड',
      'common.documentUploadDescription': 'महत्वपूर्ण अपडेट सत्यापन के लिए समर्थन दस्तावेज़ अपलोड करें',
      'common.uploadDocument': 'दस्तावेज़ अपलोड करें',
      'common.documentUploaded': 'दस्तावेज़ अपलोड किया गया',
      'common.verificationProgress': 'सत्यापन प्रगति',
      'common.cancel': 'रद्द करें',
    },
    
    ta: {
      // Patient Registration
      'patient.registration': 'நோயாளி பதிவு',
      'patient.emergency': 'அவசர பதிவு',
      'patient.basicInformation': 'அடிப்படை தகவல்',
      'patient.extendedDemographics': 'விரிவான மக்கள்தொகை',
      'patient.medicalInformation': 'மருத்துவ தகவல்',
      'patient.allergies': 'ஒவ்வாமை மற்றும் உணர்திறன்',
      'patient.allergyName': 'ஒவ்வாமை பெயர்',
      'patient.severity': 'கடுமை',
      'patient.active': 'செயலில்',
      'patient.inactive': 'செயலற்ற',
      'patient.reaction': 'எதிர்வினை/அறிகுறிகள்',
      'patient.onsetDate': 'தொடக்க தேதி',
      'patient.notes': 'குறிப்புகள்',
      'patient.criticalAllergies': 'முக்கிய ஒவ்வாமை கண்டறியப்பட்டது',
      'patient.criticalAllergiesWarning': 'நோயாளிக்கு கடுமையான அல்லது உயிருக்கு ஆபத்தான ஒவ்வாமை உள்ளது. சரியான முன்னெச்சரிக்கைகளை எடுக்கவும்.',
      'patient.noAllergies': 'ஒவ்வாமை பதிவு செய்யப்படவில்லை',
      'patient.allergySummary': 'ஒவ்வாமை சுருக்கம்',
      'patient.bloodGroup': 'இரத்த குழு',
      'patient.medicalHistory': 'மருத்துவ வரலாறு',
      'patient.medicalHistoryPlaceholder': 'தொடர்புடைய மருத்துவ வரலாற்றை உள்ளிடவும்...',
      'patient.medications': 'தற்போதைய மருந்துகள்',
      'patient.medicationsPlaceholder': 'தற்போதைய மருந்துகளின் பட்டியல்...',
      'patient.chronicConditions': 'நாள்பட்ட நிலைமைகள்',
      'patient.chronicConditionsPlaceholder': 'கமாவால் பிரிக்கப்பட்ட நாள்பட்ட நிலைமைகளை உள்ளிடவும்...',
      'patient.basicInfo': 'அடிப்படை தகவல்',
      'patient.medical': 'மருத்துவ',
      'patient.extended': 'விரிவாக்கப்பட்ட',
      'patient.consent': 'ஒப்புதல்',
      'patient.emergencyModeActive': 'அவசர பயன்முறை செயலில் - விரைவு பதிவுக்கான குறைந்த தரவு தேவைகள்',
      'patient.emergencyModeDescription': 'அடிப்படை தகவல் மற்றும் ஒரு உயிரியளவு மட்டுமே தேவை. முழு பதிவு பின்னர் முடிக்கப்படலாம்.',
      
      // Allergy severity levels
      'allergy.severity.mild': 'லேசான',
      'allergy.severity.moderate': 'மிதமான',
      'allergy.severity.severe': 'கடுமையான',
      'allergy.severity.life_threatening': 'உயிருக்கு ஆபத்தான',
      
      // Common
      'common.save': 'சேமி',
      'common.cancel': 'ரத்து',
      'common.submit': 'சமர்ப்பி',
      'common.submitting': 'சமர்ப்பிக்கிறது...',
      'common.edit': 'திருத்து',
      'common.delete': 'அழி',
      'common.view': 'காண்க',
      'common.loading': 'ஏற்றுகிறது...',
      'common.error': 'பிழை',
      'common.success': 'வெற்றி',
      'common.warning': 'எச்சரிக்கை',
      'common.info': 'தகவல்',
      'common.back': 'பின்செல்',
      'common.next': 'அடுத்து',
      'common.formComplete': 'அனைத்து தேவையான புலங்களும் முடிந்துள்ளன. நீங்கள் வடிவத்தை சமர்ப்பிக்கலாம்.',
      'common.formIncomplete': 'குறிப்பிட்ட தேவையான புலங்களை முடிக்க வேண்டும் என்றால் வடிவத்தை சமர்ப்பிக்க உதவி இருக்கும்.',
      'common.formStatus': 'வடிவ முடிவு நிலை',
      'common.completeRequiredFields': 'தேவையான புலங்களை முடிக்கவும்',
      'common.registerPatient': 'நோயாளி பதிவு',
      'common.quickRegisterPatient': 'விரைவாக நோயாளி பதிவு',
      'common.registeringPatient': 'நோயாளி பதிவு நடக்கிறது...',
      'common.addAllergy': 'ஒவ்வாமை சேர்க்கவும்',
      'common.removeAllergy': 'ஒவ்வாமை நீக்கவும்',
      'common.keyboardShortcuts': 'விசைப்பலகை குறுக்குவழிகள்',
      'common.navigation': 'வழிசெலுத்தல்',
      'common.formActions': 'வடிவ செயல்கள்',
      'common.emergencyMode': 'அவசர பயன்முறை',
      'common.biometric': 'உயிரியளவு',
      'common.help': 'உதவி',
      'common.close': 'மூடு',
      'common.ocrProcessing': 'OCR ஆவண செயலாக்கம்',
      'common.uploadDocuments': 'ஆவணங்களை பதிவேற்று',
      'common.uploadDocumentsDescription': 'தானியங்கி தரவு பிரித்தெடுப்புக்கான ஆதார் கார்டு, பான் கார்டு அல்லது ரேஷன் கார்டு பதிவேற்று',
      'common.selectDocuments': 'ஆவணங்களைத் தேர்ந்தெடுக்கவும்',
      'common.uploadedDocuments': 'பதிவேற்றப்பட்ட ஆவணங்கள்',
      'common.ocrResults': 'OCR செயலாக்க முடிவுகள்',
      'common.processingDocuments': 'ஆவணங்கள் செயலாக்கப்படுகின்றன...',
      'common.noDocumentsProcessed': 'இன்னும் எந்த ஆவணமும் செயலாக்கப்படவில்லை',
      'common.name': 'பெயர்',
      'common.dateOfBirth': 'பிறந்த தேதி',
      'common.address': 'முகவரி',
      'common.aadhaarNumber': 'ஆதார் எண்',
      'common.panNumber': 'பான் எண்',
      'common.familyMembers': 'குடும்ப உறுப்பினர்கள்',
      'common.applyToForm': 'வடிவத்திற்கு பொருந்தவும்',
      'common.reprocess': 'மறு செயலாக்கம்',
      'common.processAll': 'அனைத்து ஆவணங்களையும் செயலாக்கு',
      'common.multiFactorAuth': 'பல காரணி அங்கீகாரம்',
      'common.updateType': 'புதுப்பிப்பு வகை',
      'common.fieldToUpdate': 'புலம்',
      'common.verificationSteps': 'சரிபார்ப்பு படிகள்',
      'common.step1': 'படி 1',
      'common.step2': 'படி 2',
      'common.step3': 'படி 3',
      'common.biometricVerification': 'உயிரியளவு சரிபார்ப்பு',
      'common.biometricVerificationDescription': 'புதுப்பிப்பைத் தொடர உயிரியளவு சரிபார்ப்பை வழங்கவும்',
      'common.biometricVerified': 'உயிரியளவு சரிபார்க்கப்பட்டது',
      'common.verifyBiometric': 'உயிரியளவு சரிபார்ப்பு செய்யவும்',
      'common.otpVerification': 'OTP சரிபார்ப்பு',
      'common.otpVerificationDescription': 'உங்கள் பதிவு செய்யப்பட்ட மொபைல் எண்ணில் அனுப்பப்பட்ட OTP ஐ உள்ளிடவும்',
      'common.sendOTP': 'OTP அனுப்பு',
      'common.enterOTP': 'OTP உள்ளிடு',
      'common.documentUpload': 'ஆவண பதிவேற்றம்',
      'common.documentUploadDescription': 'முக்கியமான புதுப்பிப்பு சரிபார்ப்புக்கான ஆதரவு ஆவணத்தை பதிவேற்று',
      'common.uploadDocument': 'ஆவணத்தை பதிவேற்று',
      'common.documentUploaded': 'ஆவணம் பதிவேற்றப்பட்டது',
      'common.verificationProgress': 'சரிபார்ப்பு முன்னேற்றம்',
      'common.cancel': 'ரத்து',
    },
    
    bn: {
      // Patient Registration
      'patient.registration': 'রোগী নিবন্ধন',
      'patient.emergency': 'জরুরি নিবন্ধন',
      'patient.basicInformation': 'মৌলিক তথ্য',
      'patient.extendedDemographics': 'বিস্তৃত জনসংখ্যাতাত্ত্বিক',
      'patient.medicalInformation': 'চিকিৎসা তথ্য',
      'patient.allergies': 'অ্যালার্জি এবং সংবেদনশীলতা',
      'patient.allergyName': 'অ্যালার্জির নাম',
      'patient.severity': 'তীব্রতা',
      'patient.active': 'সক্রিয়',
      'patient.inactive': 'নিষ্ক্রিয়',
      'patient.reaction': 'প্রতিক্রিয়া/লক্ষণ',
      'patient.onsetDate': 'শুরুর তারিখ',
      'patient.notes': 'নোট',
      'patient.criticalAllergies': 'গুরুতর অ্যালার্জি সনাক্ত হয়েছে',
      'patient.criticalAllergiesWarning': 'রোগীর গুরুতর বা জীবন-হুমকি অ্যালার্জি রয়েছে। সঠিক সতর্কতা নিন।',
      'patient.noAllergies': 'কোন অ্যালার্জি রেকর্ড করা হয়নি',
      'patient.allergySummary': 'অ্যালার্জি সারসংক্ষেপ',
      'patient.bloodGroup': 'রক্তের গ্রুপ',
      'patient.medicalHistory': 'চিকিৎসা ইতিহাস',
      'patient.medicalHistoryPlaceholder': 'প্রাসঙ্গিক চিকিৎসা ইতিহাস লিখুন...',
      'patient.medications': 'বর্তমান ওষুধ',
      'patient.medicationsPlaceholder': 'বর্তমান ওষুধের তালিকা...',
      'patient.chronicConditions': 'দীর্ঘস্থায়ী অবস্থা',
      'patient.chronicConditionsPlaceholder': 'কমা দিয়ে আলাদা করা দীর্ঘস্থায়ী অবস্থা লিখুন...',
      'patient.basicInfo': 'মৌলিক তথ্য',
      'patient.medical': 'চিকিৎসা',
      'patient.extended': 'বিস্তৃত',
      'patient.consent': 'সম্মতি',
      'patient.emergencyModeActive': 'জরুরি মোড সক্রিয় - দ্রুত নিবন্ধনের জন্য কম ডেটা প্রয়োজনীয়তা',
      'patient.emergencyModeDescription': 'শুধুমাত্র মৌলিক তথ্য এবং একটি বায়োমেট্রিক প্রয়োজন। সম্পূর্ণ নিবন্ধন পরে সম্পন্ন করা যেতে পারে।',
      
      // Allergy severity levels
      'allergy.severity.mild': 'হালকা',
      'allergy.severity.moderate': 'মাঝারি',
      'allergy.severity.severe': 'গুরুতর',
      'allergy.severity.life_threatening': 'জীবন-হুমকি',
      
      // Common
      'common.save': 'সংরক্ষণ',
      'common.cancel': 'বাতিল',
      'common.submit': 'জমা দিন',
      'common.submitting': 'জমা হচ্ছে...',
      'common.edit': 'সম্পাদনা',
      'common.delete': 'মুছুন',
      'common.view': 'দেখুন',
      'common.loading': 'লোড হচ্ছে...',
      'common.error': 'ত্রুটি',
      'common.success': 'সফল',
      'common.warning': 'সতর্কতা',
      'common.info': 'তথ্য',
      'common.back': 'পিছনে',
      'common.next': 'পরবর্তী',
      'common.formComplete': 'সব প্রয়োজনীয় ক্ষেত্রগুলি সম্পূর্ণ করা হয়েছে। আপনি ফর্মটি জমা দিতে পারেন।',
      'common.formIncomplete': 'কিছু প্রয়োজনীয় ক্ষেত্রগুলি সম্পূর্ণ করার জন্য কৃপয় করুন যাতে ফর্মটি জমা দিতে সহায়তা থাকে।',
      'common.formStatus': 'ফর্ম সম্পূর্ণতা অবস্থা',
      'common.completeRequiredFields': 'প্রয়োজনীয় ক্ষেত্রগুলি সম্পূর্ণ করুন',
      'common.registerPatient': 'রোগী নিবন্ধন',
      'common.quickRegisterPatient': 'তথ্যাদি সহজ রোগী নিবন্ধন',
      'common.registeringPatient': 'রোগী নিবন্ধন নটিয়ার হচ্ছে...',
      'common.addAllergy': 'অ্যালার্জি যোগ করুন',
      'common.removeAllergy': 'অ্যালার্জি সরিয়ে দিন',
      'common.keyboardShortcuts': 'কীবোর্ড শর্টকাট',
      'common.navigation': 'নেভিগেশন',
      'common.formActions': 'ফর্ম ক্রিয়া',
      'common.emergencyMode': 'জরুরি মোড',
      'common.biometric': 'বায়োমেট্রিক',
      'common.help': 'সাহায্য',
      'common.close': 'বন্ধ করুন',
      'common.ocrProcessing': 'OCR ডকুমেন্ট প্রসেসিং',
      'common.uploadDocuments': 'ডকুমেন্ট আপলোড করুন',
      'common.uploadDocumentsDescription': 'স্বয়ংক্রিয় ডেটা এক্সট্রাকশনের জন্য আধার কার্ড, প্যান কার্ড, বা রেশন কার্ড আপলোড করুন',
      'common.selectDocuments': 'ডকুমেন্ট নির্বাচন করুন',
      'common.uploadedDocuments': 'আপলোড করা ডকুমেন্ট',
      'common.ocrResults': 'OCR প্রসেসিং ফলাফল',
      'common.processingDocuments': 'ডকুমেন্ট প্রসেসিং হচ্ছে...',
      'common.noDocumentsProcessed': 'এখনও কোন ডকুমেন্ট প্রসেস করা হয়নি',
      'common.name': 'নাম',
      'common.dateOfBirth': 'জন্ম তারিখ',
      'common.address': 'ঠিকানা',
      'common.aadhaarNumber': 'আধার নম্বর',
      'common.panNumber': 'প্যান নম্বর',
      'common.familyMembers': 'পরিবারের সদস্য',
      'common.applyToForm': 'ফর্মে প্রয়োগ করুন',
      'common.reprocess': 'পুনরায় প্রসেস করুন',
      'common.processAll': 'সব ডকুমেন্ট প্রসেস করুন',
      'common.multiFactorAuth': 'মাল্টি-ফ্যাক্টর অথেনটিকেশন',
      'common.updateType': 'আপডেট টাইপ',
      'common.fieldToUpdate': 'ফিল্ড',
      'common.verificationSteps': 'যাচাইকরণ ধাপ',
      'common.step1': 'ধাপ 1',
      'common.step2': 'ধাপ 2',
      'common.step3': 'ধাপ 3',
      'common.biometricVerification': 'বায়োমেট্রিক যাচাইকরণ',
      'common.biometricVerificationDescription': 'আপডেট চালিয়ে যাওয়ার জন্য বায়োমেট্রিক যাচাইকরণ প্রদান করুন',
      'common.biometricVerified': 'বায়োমেট্রিক যাচাইকৃত',
      'common.verifyBiometric': 'বায়োমেট্রিক যাচাই করুন',
      'common.otpVerification': 'OTP যাচাইকরণ',
      'common.otpVerificationDescription': 'আপনার নিবন্ধিত মোবাইল নম্বরে পাঠানো OTP লিখুন',
      'common.sendOTP': 'OTP পাঠান',
      'common.enterOTP': 'OTP লিখুন',
      'common.documentUpload': 'ডকুমেন্ট আপলোড',
      'common.documentUploadDescription': 'সমালোচনামূলক আপডেট যাচাইকরণের জন্য সহায়ক ডকুমেন্ট আপলোড করুন',
      'common.uploadDocument': 'ডকুমেন্ট আপলোড করুন',
      'common.documentUploaded': 'ডকুমেন্ট আপলোড হয়েছে',
      'common.verificationProgress': 'যাচাইকরণ অগ্রগতি',
      'common.cancel': 'বাতিল',
    }
  }
};

const languageReducer = (state, action) => {
  switch (action.type) {
    case 'SET_LANGUAGE':
      return {
        ...state,
        currentLanguage: action.payload,
      };
    default:
      return state;
  }
};

export const LanguageProvider = ({ children }) => {
  const [state, dispatch] = useReducer(languageReducer, initialState);

  const setLanguage = (language) => {
    dispatch({ type: 'SET_LANGUAGE', payload: language });
    localStorage.setItem('preferredLanguage', language);
  };

  const translate = (key, fallback = key) => {
    const currentTranslations = state.translations[state.currentLanguage];
    return currentTranslations?.[key] || fallback;
  };

  const currentLanguage = state.currentLanguage;

  useEffect(() => {
    const savedLanguage = localStorage.getItem('preferredLanguage');
    if (savedLanguage && state.translations[savedLanguage]) {
      setLanguage(savedLanguage);
    }
  }, []);

  const context = {
    currentLanguage,
    setLanguage,
    translate,
    availableLanguages: Object.keys(state.translations),
  };

  return (
    <LanguageContext.Provider value={context}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 